name: Gradle Build Project

on: workflow_dispatch

jobs:
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [ '17' ]
    name: ${{ matrix.os }}
    
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3.9.0
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Verify JAVA_HOME
      run: echo $JAVA_HOME
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    - name: Execute build
      run: ./gradlew --info --stacktrace build
    - name: Execute jlinkZip
      run: ./gradlew --info --stacktrace jlinkZip
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: ${{ matrix.java }}-${{ matrix.os }}-Image
        # A file, directory or wildcard pattern that describes what to upload
        path: build/AsciiImage.zip
        # The desired behavior if no files are found using the provided path.
        retention-days: 2
